version: "3.7"

services: 
    spark-master:
        image: gettyimages/spark
        command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
        hostname: spark-master
        container_name: spark-master
        environment:
            MASTER: spark://spark-master:7077
            SPARK_CONF_DIR: /conf
            SPARK_PUBLIC_DNS: spark-master.localhost
        volumes:
            - ./spark/conf/master:/conf
            - ./spark/data:/tmp/data
    spark-wk1:
        image: gettyimages/spark
        command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
        hostname: spark-wk1
        container_name: spark-wk1
        environment:
            SPARK_CONF_DIR: /conf
            SPARK_WORKER_CORES: 2
            SPARK_WORKER_MEMORY: 1g
            SPARK_WORKER_PORT: 8881
            SPARK_WORKER_WEBUI_PORT: 8081
            SPARK_PUBLIC_DNS: spark-wk1.localhost
        links:
            - master
        volumes:
            - ./spark/conf/wk1:/conf
            - ./spark/data:/tmp/data