version: "3.7"

services: 
    reverseproxy:
        image: nginx:${REVERSE_PROXY_VERSION}
        volumes:
            - ./nginx/spark.conf:/etc/nginx/conf.d/spark.conf:ro
    
    spark-master:
        image: gettyimages/spark
        command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
        hostname: spark-master
        container_name: spark-master
        environment:
            MASTER: ${SPARK_MASTER}
            SPARK_CONF_DIR: /conf
            SPARK_PUBLIC_DNS: spark-master.localhost
        volumes:
            - ./conf/master:/conf
            - ./data:/tmp/data